name: Deploy Strapi
on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: $ubuntu
      EC2_HOST: ${{ secrets.HARIPRIYA_EC2_HOST }}
      PRIVATE_KEY: ${{ secrets.HARIPRIYA_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.HARIPRIYA_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Deploy Strapi Application
        run: |
          # Install Strapi globally
          sudo npm install strapi@beta -g

          # Create a new Strapi project
          strapi new priya-project --dbclient=sqlite

          # Navigate to the new project directory
          cd priya-project

          # Start the Strapi application using pm2
          pm2 start npm --name 'strapi' -- run develop
