name: Deploy Strapi
on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: $ubuntu
      EC2_HOST: ${{ secrets.HARIPRIYA_EC2_HOST }}
      PRIVATE_KEY: ${{ secrets.HARIPRIYA_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.HARIPRIYA_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Deploy Strapi Application
        run: |
          cd simple-strapi
          echo "const strapi = require('@strapi/strapi');
          strapi().start();" > server.js
          pm2 start server.js
